#!/bin/sh

GETTEXT="gettext -d horoscope"

echo "Enter your horscope: "
read sign

#echo $($GETTEXT "$sign")

DIALOG=gdialog || DIALOG=dialog

choice=$($DIALOG --title "`$GETTEXT \"Selection for\"`" "$sign" --menu "`$GETTEXT \"Signs\"`" 15 50 8 \
	  "$(cat ./data/Aries)" "`$GETTEXT \"Aries\"`" \
	  "$(cat ./data/Taurus)" "`$GETTEXT \"Taurus\"`" \
	  "$(cat ./data/Gemini)" "`$GETTEXT \"Gemini\"`" \
	  "$(cat ./data/Virgo)" "`$GETTEXT \"Virgo\"`" \
	  "$(cat ./data/Leo)" "`$GETTEXT \"Leo\"`" \
	  "$(cat ./data/Libra)" "`$GETTEXT \"Libra\"`"

	    3>&2 2>&1 1>&3)

echo "$choice"

exit