#!/bin/bash


today="$(date +'%A')"

echo "Enter your group(1-7): "
read loadsheddinggroup

schedule=$(curl 'https://acpmasquerade-nepal-loadshedding-schedule-by-sparrow-sms.p.mashape.com/schedule.php?format=format%3Djson&group='$loadsheddinggroup \
  -H 'X-Mashape-Key: ciC1tzZvFlmsh0YYcAJpaFIo7O4fp146MKpjsnts1ZHez3NJvv' )

echo $schedule

exit